### ISSUE TITLE
Error: spawn netstat ENOENT

### ISSUE THREAD

**Issue by gokhanefendi** [sindresorhus/fkill-cli#38]
Hi, `fkill` command does not respond to my situation and after `control+c` it shows that error message; 

```
Error: spawn netstat ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

OS: Ubuntu 16.04.4 LTS
Npm: 3.5.2
Node: v4.2.6

And then I realized missing netstat.

I installed netstat using `apt-get install net-tools`

It works fine! 👍

**Comment by sindresorhus** [comment]
`netstat` is no longer used on Linux, so this can be closed now: https://github.com/kevva/pid-from-port/blob/02d67228b6593a0dc6095fb4a6cb101cadb89f1f/index.js
