### ISSUE TITLE
Aggregate Error in mac os HighSierra

### ISSUE THREAD

**Issue by zymr-keshav** [sindresorhus/fkill-cli#50]
Macos v 10.1.3.3 ( High Sierra)

There is a process running on the port 8083 ; I have checked from `lsof` command  and When I try to kill a process using port number than it gives following error:

> fkill :8083

> [AggregateError:
>     Error: Killing process 64708 failed: Process doesn't exist
>         at Array.map (<anonymous>)
>         at processExists.all.then.then (/usr/local/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
>         at <anonymous>
>     at processExists.all.then.then (/usr/local/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)](url)
> 
>

**Comment by sindresorhus** [comment]
@kevva Any idea what this could be?

**Comment by tjconcept** [comment]
Saw this too.

```
$ fkill gpg
? Error killing process. Would you like to use the force? Yes
AggregateError: 
    Error: Killing process gpg failed: Process doesn't exist
        at Array.map (<anonymous>)
        at processExists.all.then.then (/Users/tj/.npm-config/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
    at processExists.all.then.then (/Users/tj/.npm-config/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
