### ISSUE TITLE
unexpected identifier on first install

### ISSUE THREAD

**Issue by maxandersen** [sindresorhus/fkill-cli#53]
I'm sure this is just some node.js mismatch but just wanted to let you know that after running

`npm install --global fkill-cli`

then on first run of `fkill` I get:

```
/usr/local/lib/node_modules/fkill-cli/cli.js:86
const handleFkillError = async processes => {
                               ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by maxandersen** [comment]
fixed it by ensuring I was running node 8. 

```
nvm install 8.0
```

after that running `fkill` worked.

I was running with node 6.9 when I got the original error.
