### ISSUE TITLE
v6.0.0 interactive mode not launching on Windows

### ISSUE THREAD

**Issue by skubi** [sindresorhus/fkill-cli#68]
Version 6.0.0 (latest) not launching interactive mode on Windows.

Steps to reproduce:
```
>npm --global install fkill-cli
+ fkill-cli@6.0.0
added 155 packages from 67 contributors in 3.904s

>fkill
TypeError: Expected a number
    at assertNumber (\AppData\Roaming\npm\node_modules\fkill-cli\node_modules\num-sort\index.js:5:9)
    at Object.exports.descending (AppData\Roaming\npm\node_modules\fkill-cli\node_modules\num-sort\index.js:16:2)
    at preferHighPerformanceImpact (\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:32:55)
    at preferHeurisicallyInterestingProcesses (\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:43:11)
    at Array.sort (<anonymous>)
    at filterProcesses (\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:67:4)
    at Object.source (\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:123:37)
    at AutocompletePrompt.search (\AppData\Roaming\npm\node_modules\fkill-cli\node_modules\inquirer-autocomplete-prompt\index.js:177:32)
    at AutocompletePrompt._run (\AppData\Roaming\npm\node_modules\fkill-cli\node_modules\inquirer-autocomplete-prompt\index.js:65:10)
    at \AppData\Roaming\npm\node_modules\fkill-cli\node_modules\inquirer\lib\prompts\base.js:57:12
```

When installing v5.2.0, all works as expected:
```
>npm --global uninstall fkill-cli
removed 155 packages in 1.251s

>npm --global install fkill-cli@v5.2.0
+ fkill-cli@5.2.0
added 148 packages from 72 contributors in 8.038s

>fkill
? Running processes: (Use arrow keys or type to search)
> System Idle Process 0 :57519 :57521 :57522 :57523
  System 4 :445 :9009 :50160 :139
  Secure System 72
  svchost.exe 96
  svchost.exe 104
  lsass.exe 112
  Registry 144
  smss.exe 532
  SearchProtocolHost.exe 712
  browser_broker.exe 808
(Move up and down to reveal more choices)
```

Other versions:
```
>node -v
v13.9.0

>npm -v
6.13.7
```

**Comment by sindresorhus** [comment]
// @stroncium
