### ISSUE TITLE
fkill crashes on Node v8.17.0

### ISSUE THREAD

**Issue by gvsandeep2647** [sindresorhus/fkill-cli#77]
Error Stack:

```
/Users/g.v.sandeep/.nvm/versions/node/v8.17.0/lib/node_modules/fkill-cli/node_modules/fkill/node_modules/ps-list/index.js:80
const psOutputRegex = /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/;
                      ^

SyntaxError: Invalid regular expression: /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/: Invalid group
    at Object.<anonymous> (/Users/g.v.sandeep/.nvm/versions/node/v8.17.0/lib/node_modules/fkill-cli/node_modules/fkill/node_modules/ps-list/index.js:80:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/g.v.sandeep/.nvm/versions/node/v8.17.0/lib/node_modules/fkill-cli/node_modules/fkill/index.js:8:16)
    at Module._compile (module.js:653:30)
```

Steps to Reproduce:
Run any fkill command.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/fkill-cli/blob/fd8c3b80b55a619e9b4d4d7378761e3037b0b8a5/package.json#L17
